{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_when_no_pds_response_cache_available", "rerun": "0"}, "1": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Then \"the response includes X-Cache-Status header with a value Hit\". Line 18 in scenario \"When PDS response's cached\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/PDSCache/1_pds_cache.feature\"\n", "test_name": "test_when_pds_responses_cached", "rerun": "0"}, "2": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: When \"cache returns 200 status\". Line 24 in scenario \"When cached PDS response has expired\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/PDSCache/1_pds_cache.feature\"\n", "test_name": "test_when_cached_pds_response_has_expired", "rerun": "0"}}, "suite_name": "test_api/test_pds_cache.py"}}}, "date": "July 12, 2024", "start_time": 1720780232.489923, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}